# Generated by Django 3.0.4 on 2020-04-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('identification_number', models.CharField(max_length=30)),
                ('student_number', models.CharField(max_length=50)),
                ('year_level', models.CharField(choices=[('1', 'First Year'), ('2', 'second year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Firth Year'), ('6', 'Sixth Year'), ('7', 'Seventh Year')], max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=12)),
                ('telephone_number', models.CharField(max_length=12)),
                ('birth_date', models.DateField(auto_now=True)),
                ('current_address', models.CharField(max_length=300)),
                ('postal_address', models.CharField(max_length=300)),
                ('contact_person', models.CharField(max_length=250)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], max_length=10)),
                ('address_of_contact', models.CharField(max_length=300)),
            ],
        ),
    ]
