# Generated by Django 3.0.4 on 2020-04-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200425_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_of_contact',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number_of_contact',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='telephone_number_of_contact',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
