# Generated by Django 3.0.4 on 2020-04-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200425_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_of_contact',
            field=models.CharField(max_length=150),
        ),
    ]
