# Generated by Django 3.0.4 on 2020-03-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField(verbose_name='Bio')),
                ('dob', models.DateField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_number', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('finance', 'Finance'), ('management', 'Management'), ('engineering', 'Engineering'), ('design', 'Design'), ('arts_and_music', 'Arts & Music'), ('it_&_computers', 'Information Technology')], max_length=255)),
                ('author', models.ManyToManyField(to='stocksystem.Author')),
            ],
        ),
    ]
